services:
  app:
    build: .
    #image: ghcr.io/cris590/ordencompra-back-v2
    container_name: backend_ordenes
    ports:
      - "3200:3000"
    volumes:
      # - .:/usr/src/app
      # - /usr/src/app/node_modules
      - ./uploads:/usr/src/app/uploads
      - ./documents_storage:/usr/src/app/documents_storage
    env_file:
      - .env 
    command: npm start
