name: Publish Docker image

on:
  push: 
    branches: ["production", "development"]
  pull_request:
    branches: ["production", "development"]

jobs:
  create-docker-image:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@65b78e6e13532edd9afa3aa52ac7964289d1a9c1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.TOKEN_GITHUB }}

      - name: Build and push Docker image
        run: |
          docker build . --tag ghcr.io/cris590/ordencompra-back-v2-${{ github.ref_name }}
          docker push ghcr.io/cris590/ordencompra-back-v2-${{ github.ref_name }}

  deploy:
    needs: create-docker-image
    runs-on: ubuntu-latest
    steps:
      - name: Install sshpass
        run: sudo apt-get install -y sshpass

      - name: SSH into server and deploy
        run: |
          sshpass -p ${{ secrets.AUTH_PASS }} ssh -o StrictHostKeyChecking=no ${{ secrets.AUTH_SERVER }} << EOF
          sh  /services/deploy.sh ${{ github.ref_name }}      
          EOF
